CREATE TABLE todos (
       id BIGSERIAL PRIMARY KEY,
       title VARCHAR(200) NOT NULL,
       done BOOLEAN NOT NULL DEFAULT FALSE,
       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
